export const projects = [
  {
    id: '1',
    screenshot: '/assets/images/handyman.webp',
    title: 'Handyman Sant Quirze',
    subTitle: 'Landing Page Handyman',
    stack: [
      'astro',
      'typescript',
      'react',
      'tailwindcss',
      'figma',
    ],
    description: `Handymansqv es una landing page para un servicio local de mantenimiento en Sant Quirze del Vallès, España. El sitio web se creó con Astro, un generador de sitios estáticos moderno que combina lo mejor de los generadores de sitios estáticos tradicionales y las herramientas de creación modernas. El sitio presenta un diseño limpio y minimalista, con un enfoque en la experiencia del usuario y la accesibilidad. La landing page es totalmente responsiva y está optimizada para el rendimiento, lo que garantiza una experiencia fluida y sin problemas en todos los dispositivos.`,
    date: 'Enero 31, 2025',
    github: 'https://github.com/Jhersonnpa/handyman',
    live: 'https://handymansqv.com/',
    color: '#F7FBFC',
    btnBg: '#201F1F',
    btnBgHover: '#0C0C0D',
    cardBg: '#201F1F',
  },
  {
    id: '2',
    screenshot: '/assets/images/pizzapolitan.webp',
    title: 'Pizzapolitan',
    subTitle: 'Landing Page Pizzapolitan',
    stack: [
      'astro',
      'typescript',
      'react',
      'tailwindcss',
      'figma',
    ],
    description:
      'Pizzapolitan es una landing page para una pizzería ficticia. El sitio web se creó con Astro, un generador de sitios estáticos moderno que combina lo mejor de los generadores de sitios estáticos tradicionales y las herramientas de creación modernas. El sitio presenta un diseño limpio y minimalista, con un enfoque en la experiencia del usuario y la accesibilidad. La landing page es totalmente responsiva y está optimizada para el rendimiento, lo que garantiza una experiencia fluida y sin inconvenientes en todos los dispositivos.',
    date: 'Oct 27, 2024',
    github: 'https://github.com/Jhersonnpa/Pizzapolitan',
    live: 'https://pizzapolitan.com/',
    color: '#056839',
    btnBg: '#056839',
    btnBgHover: '#C10023',
    cardBg: '#201F1F',
  },
  {
    id: '3',
    screenshot: '/assets/images/sqsr.webp',
    title: 'Sant Quirze Sobre Rodes',
    subTitle: 'Página web de Sant Quirze Sobre Rodes',
    stack: [
      'astro',
      'typescript',
      'react',
      'tailwindcss',
      'figma',
      'shadcn',
    ],
    description:
      'Sant Quirze Sobre Rodes es un sitio web para un evento ciclista local en Sant Quirze del Vallès, España. El sitio web se creó con Astro, un generador de sitios estáticos moderno que combina lo mejor de los generadores de sitios estáticos tradicionales y las herramientas de creación modernas. El sitio presenta un diseño limpio y minimalista, con un enfoque en la experiencia del usuario y la accesibilidad. La página de destino es totalmente responsiva y está optimizada para el rendimiento, lo que garantiza una experiencia fluida y sin problemas en todos los dispositivos.',
    date: 'Sep 2, 2024',
    github: 'https://github.com/Jhersonnpa/sqsr',
    live: 'https://sqsr-dev.vercel.app/',
    color: '#EA580C',
    btnBg: '#EA580C',
    btnBgHover: 'rgba(30,27,75)',
    cardBg: '#0C0C0D',
  },
  {
    id: '4',
    screenshot: '/assets/images/pinopack.webp',
    title: 'Pino Pack',
    subTitle: 'Pino Pack página web',
    stack: ['Wordpress', 'Elementor','Figma'],
    description: `Pino Pack es una página web de comercio electrónico para una tienda de productos de embalaje. El sitio web se creó con WordPress y Elementor, lo que permite a los propietarios de la tienda gestionar fácilmente el contenido y las ventas. El diseño del sitio web se basó en un diseño de Figma proporcionado por el cliente, que se adaptó y personalizó para satisfacer las necesidades y preferencias del cliente. La página web es totalmente responsiva y está optimizada para el rendimiento, lo que garantiza una experiencia fluida y sin problemas en todos los dispositivos.`,
    date: 'Junio 2, 2022',
    github: '',
    live: 'https://www.pinopack.com/es/',
    color: '#0814BF',
    btnBg: '#0814BF',
    btnBgHover: '#0814BF',
    cardBg: '#21222E',
  },
  {
    id: '5',
    screenshot: '/assets/images/alkila.webp',
    title: 'Alkila Trasteros',
    subTitle: 'Alkila Trasteros págona web',
    stack: ['WordPress', 'Elementor', 'Figma'],
    description: `Alkila Trasteros es una página web de comercio electrónico para una empresa de alquiler de trasteros. El sitio web se creó con WordPress y Elementor, lo que permite a los propietarios de la empresa gestionar fácilmente el contenido y las ventas. El diseño del sitio web se basó en un diseño de Figma proporcionado por el cliente, que se adaptó y personalizó para satisfacer las necesidades y preferencias del cliente. La página web es totalmente responsiva y está optimizada para el rendimiento, lo que garantiza una experiencia fluida y sin problemas en todos los dispositivos.`,
    date: 'Abril 15, 2022',
    github: '',
    live: 'https://alkilatrasteros.es/',
    color: '#E4042D',
    btnBg: '#E4042D',
    btnBgHover: '#8f9090',
    cardBg: '#1B1C1C',
  },
];
