export const projects = [
  {
    id: '1',
    screenshot: '/assets/images/handyman.webp',
    title: 'Handyman Sant Quirze',
    subTitle: 'Landing Page Handyman',
    stack: [
      'astro',
      'typescript',
      'react',
      'tailwindcss',
      'figma',
    ],
    description: `Handymansqv is a landing page for a local handyman service in Sant Quirze del Vallès, Spain. The website was built using Astro, a modern static site generator that combines the best of traditional static site generators and modern build tools. The site features a clean and minimalistic design, with a focus on user experience and accessibility. The landing page is fully responsive and optimized for performance, ensuring a smooth and seamless experience across all devices.`,
    date: 'Enero 31, 2025',
    github: 'https://github.com/Jhersonnpa/handyman',
    live: 'https://handymansqv.com/',
    color: '#F7FBFC',
    btnBg: '#201F1F',
    btnBgHover: '#0C0C0D',
    cardBg: '#201F1F',
  },
  {
    id: '2',
    screenshot: '/assets/images/pizzapolitan.webp',
    title: 'Pizzapolitan',
    subTitle: 'Landing Page Pizzapolitan',
    stack: [
      'astro',
      'typescript',
      'react',
      'tailwindcss',
      'figma',
    ],
    description:
      'Pizzapolitan is a landing page for a fictional pizza restaurant. The website was built using Astro, a modern static site generator that combines the best of traditional static site generators and modern build tools. The site features a clean and minimalistic design, with a focus on user experience and accessibility. The landing page is fully responsive and optimized for performance, ensuring a smooth and seamless experience across all devices.',
    date: 'Oct 27, 2024',
    github: 'https://github.com/Jhersonnpa/Pizzapolitan',
    live: 'https://pizzapolitan.com/',
    color: '#056839',
    btnBg: '#056839',
    btnBgHover: '#C10023',
    cardBg: '#201F1F',
  },
  {
    id: '3',
    screenshot: '/assets/images/sqsr.webp',
    title: 'Sant Quirze Sobre Rodes',
    subTitle: 'Página web de Sant Quirze Sobre Rodes',
    stack: [
      'astro',
      'typescript',
      'react',
      'tailwindcss',
      'figma',
      'shadcn',
    ],
    description:
      'Sant Quirze Sobre Rodes is a website for a local cycling event in Sant Quirze del Vallès, Spain. The website was built using Astro, a modern static site generator that combines the best of traditional static site generators and modern build tools. The site features a clean and minimalistic design, with a focus on user experience and accessibility. The landing page is fully responsive and optimized for performance, ensuring a smooth and seamless experience across all devices.',
    date: 'Sep 2, 2024',
    github: 'https://github.com/Jhersonnpa/sqsr',
    live: 'https://sqsr-dev.vercel.app/',
    color: '#EA580C',
    btnBg: '#EA580C',
    btnBgHover: 'rgba(30,27,75)',
    cardBg: '#0C0C0D',
  },
  {
    id: '4',
    screenshot: '/fintechracy.png',
    title: 'Fintechracy',
    subTitle: 'Fintechracy official website',
    stack: ['react', 'tailwindcss', 'framer motion', 'shadcn'],
    description: `Fintechracy is on a mission to eliminate paper receipts by providing innovative software solutions. After two unsuccessful attempts to develop a professional website, I stepped in to deliver a final version that met the company's vision and market standards. The website, built with React, Tailwind CSS, ShadCN, and Framer Motion, features smooth animations, complete responsiveness, and multi-language support for a seamless global user experience.`,
    date: 'Jan 2, 2024',
    github: '',
    live: 'https://www.fintechracy.org/',
    color: 'rgba(34,197,94)',
    btnBg: 'rgba(22,101,52,0.5)',
    btnBgHover: 'rgba(5,46,22)',
    cardBg: 'rgba(22,101,52,0.05)',
  },
  {
    id: '5',
    screenshot: '/chatbotify.png',
    title: 'ChatBotify Gallery',
    subTitle: 'ChatBotify Gallery website',
    stack: ['react', 'tailwindcss', 'figma'],
    description: `Chatbotify Gallery is an (open-source) project showcasing customizable chatbot designs. When I joined the team, one major blocker was the lack of a unified color palette and design system. I addressed this by creating a cohesive palette that aligned with the application's style and feel, streamlining the design process for the entire team. My contributions include designing and developing the About page using React and Tailwind CSS, as well as working on the Theme Builder page—a feature enabling users to customize chatbots to match their tone and branding.`,
    date: 'Jan 2, 2024',
    github: 'https://github.com/adel-gu/react-chatbotify-gallery-website',
    live: 'https://gallery.react-chatbotify.com/',
    color: 'rgba(6,182,212)',
    btnBg: 'rgba(7,89,133,0.5)',
    btnBgHover: 'rgba(8,47,73)',
    cardBg: 'rgba(7,89,133,0.05)',
  },
];
