export const projects = [
  {
    id: '1',
    screenshot: '/assets/images/handyman.webp',
    title: 'Handyman Sant Quirze',
    subTitle: 'Landing Page Handyman',
    stack: [
      'astro',
      'typescript',
      'react',
      'tailwindcss',
      'figma',
    ],
    description: `Landing page diseñada para un servicio de mantenimiento en Sant Quirze del Vallès, España. Creada con Astro para ofrecer una navegación rápida y fluida, con un diseño moderno y optimizado para dispositivos móviles.`,
    date: 'Enero 31, 2025',
    github: 'https://github.com/Jhersonnpa/handyman',
    live: 'https://handymansqv.com/',
    color: '#F7FBFC',
    btnBg: '#201F1F',
    btnBgHover: '#0C0C0D',
    cardBg: '#201F1F',
  },
  {
    id: '2',
    screenshot: '/assets/images/pizzapolitan.webp',
    title: 'Pizzapolitan',
    subTitle: 'Landing Page Pizzapolitan',
    stack: [
      'astro',
      'typescript',
      'react',
      'tailwindcss',
      'figma',
    ],
    description:
      'Página promocional para una pizzería ficticia, diseñada con Astro para garantizar velocidad y rendimiento. Cuenta con una interfaz atractiva y una experiencia de usuario intuitiva.',
    date: 'Oct 27, 2024',
    github: 'https://github.com/Jhersonnpa/Pizzapolitan',
    live: 'https://pizzapolitan.com/',
    color: '#056839',
    btnBg: '#056839',
    btnBgHover: '#C10023',
    cardBg: '#201F1F',
  },
  {
    id: '3',
    screenshot: '/assets/images/sqsr.webp',
    title: 'Sant Quirze Sobre Rodes',
    subTitle: 'Página web del evento ciclista',
    stack: [
      'astro',
      'typescript',
      'react',
      'tailwindcss',
      'figma',
      'shadcn',
    ],
    description:
      'Sitio web informativo para un evento ciclista en Sant Quirze del Vallès, con un diseño atractivo y adaptado para dispositivos móviles.',
    date: 'Sep 2, 2024',
    github: 'https://github.com/Jhersonnpa/sqsr',
    live: 'https://sqsr-dev.vercel.app/',
    color: '#EA580C',
    btnBg: '#EA580C',
    btnBgHover: 'rgba(30,27,75)',
    cardBg: '#0C0C0D',
  },
  {
    id: '4',
    screenshot: '/assets/images/pinopack.webp',
    title: 'Pino Pack',
    subTitle: 'E-commerce para embalajes',
    stack: ['Wordpress', 'Elementor','Figma'],
    description: `Tienda online especializada en productos de embalaje, desarrollada con WordPress y Elementor para facilitar la gestión del contenido y las ventas.`,
    date: 'Junio 2, 2022',
    github: '',
    live: 'https://www.pinopack.com/es/',
    color: '#0814BF',
    btnBg: '#0814BF',
    btnBgHover: '#0814BF',
    cardBg: '#21222E',
  },
  {
    id: '5',
    screenshot: '/assets/images/alkila.webp',
    title: 'Alkila Trasteros',
    subTitle: 'E-commerce para alquiler de trasteros',
    stack: ['WordPress', 'Elementor', 'Figma'],
    description: `Página web comercial para una empresa de alquiler de trasteros, diseñada para optimizar la conversión y facilitar la administración del negocio.`,
    date: 'Abril 15, 2022',
    github: '',
    live: 'https://alkilatrasteros.es/',
    color: '#E4042D',
    btnBg: '#E4042D',
    btnBgHover: '#8f9090',
    cardBg: '#1B1C1C',
  },
];

